import React, { useState } from 'react';
import { ArrowLeft, Mail, Send, ShieldCheck } from 'lucide-react';
import { api } from '../services/api';
import { ThemeToggle } from '../components/Layout/ThemeToggle';

export const PasswordRecovery: React.FC<{ onBack: () => void }> = ({ onBack }) => {
  const [email, setEmail] = useState(''); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(null); setLoading(true); try { const res = await api.post('/auth/forgot-password', { email }); setMessage(res.data.message); } catch (err: any) { setError(err.response?.data?.error || 'Não foi possível processar a solicitação.'); } finally { setLoading(false); } };
  return <div className="min-h-dvh bg-slate-950 flex items-center justify-center p-4 relative"><ThemeToggle className="absolute right-4 top-4" /><div className="surface-elevated w-full max-w-md rounded-2xl p-6 sm:p-8 space-y-5"><div className="flex items-center gap-3"><div className="icon-box h-11 w-11 rounded-xl bg-cyan-500/10 text-cyan-400"><Mail className="h-5 w-5" /></div><div><h1 className="if-text text-xl font-black">Recuperar senha</h1><p className="if-text-secondary text-xs">Digite o e-mail cadastrado na sua conta.</p></div></div>{message ? <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/30 success-text text-sm">{message}</div> : <form onSubmit={submit} className="space-y-4"><label className="block if-text-secondary text-xs font-semibold">E-mail<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="settings-control mt-1.5 w-full rounded-xl px-3.5 py-3" autoComplete="email" /></label>{error && <p className="danger-text text-xs">{error}</p>}<button disabled={loading} className="if-button-primary min-h-11 w-full rounded-xl inline-flex items-center justify-center gap-2 font-bold">{loading ? 'Enviando...' : <><Send className="h-4 w-4" /> Enviar link de recuperação</>}</button></form>}<button onClick={onBack} className="action-text text-xs inline-flex items-center gap-1.5"><ArrowLeft className="h-3.5 w-3.5" />Voltar para o login</button><div className="border-t if-divider pt-4 if-text-muted text-[11px] flex items-center justify-center gap-2"><ShieldCheck className="h-3.5 w-3.5" />Não revelamos se o e-mail está cadastrado.</div></div></div>;
};
