import React, { useMemo, useState } from 'react';
import { ArrowLeft, Eye, EyeOff, KeyRound, CheckCircle2 } from 'lucide-react';
import { api } from '../services/api';
import { ThemeToggle } from '../components/Layout/ThemeToggle';

const requirements = [['8 ou mais caracteres', (v: string) => v.length >= 8], ['letra maiúscula', (v: string) => /[A-Z]/.test(v)], ['letra minúscula', (v: string) => /[a-z]/.test(v)], ['número', (v: string) => /[0-9]/.test(v)], ['caractere especial', (v: string) => /[^A-Za-z0-9]/.test(v)]] as const;
export const ResetPassword: React.FC<{ token: string; onBack: () => void }> = ({ token, onBack }) => {
  const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [show, setShow] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const valid = useMemo(() => requirements.every(([, check]) => check(password)), [password]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(null); if (password !== confirmation) { setError('As senhas não coincidem.'); return; } setLoading(true); try { const res = await api.post('/auth/reset-password', { token, password, passwordConfirmation: confirmation }); setMessage(res.data.message); } catch (err: any) { setError(err.response?.data?.error || 'Este link de recuperação é inválido ou expirou.'); } finally { setLoading(false); } };
  return <div className="min-h-dvh bg-slate-950 flex items-center justify-center p-4 relative"><ThemeToggle className="absolute right-4 top-4" /><div className="surface-elevated w-full max-w-md rounded-2xl p-6 sm:p-8 space-y-5"><div className="flex items-center gap-3"><div className="icon-box h-11 w-11 rounded-xl bg-cyan-500/10 text-cyan-400"><KeyRound className="h-5 w-5" /></div><div><h1 className="if-text text-xl font-black">Redefinir senha</h1><p className="if-text-secondary text-xs">Crie uma nova senha para sua conta.</p></div></div>{message ? <div className="space-y-4"><div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/30 success-text text-sm flex gap-2"><CheckCircle2 className="h-4 w-4 shrink-0" />{message}</div><button onClick={onBack} className="if-button-primary w-full rounded-xl min-h-11">Voltar para o login</button></div> : <form onSubmit={submit} className="space-y-4"><label className="block if-text-secondary text-xs font-semibold">Nova senha<div className="relative mt-1.5"><input required type={show ? 'text' : 'password'} value={password} onChange={(e) => setPassword(e.target.value)} className="settings-control w-full rounded-xl px-3.5 py-3 pr-11" autoComplete="new-password" /><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 if-text-muted" aria-label={show ? 'Ocultar senha' : 'Mostrar senha'}>{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></label><label className="block if-text-secondary text-xs font-semibold">Confirmar nova senha<input required type={show ? 'text' : 'password'} value={confirmation} onChange={(e) => setConfirmation(e.target.value)} className="settings-control mt-1.5 w-full rounded-xl px-3.5 py-3" autoComplete="new-password" /></label><ul className="grid grid-cols-2 gap-1 text-[11px] if-text-muted">{requirements.map(([label, check]) => <li key={label} className={check(password) ? 'success-text' : ''}>{check(password) ? '✓' : '○'} {label}</li>)}</ul>{error && <p className="danger-text text-xs">{error}</p>}<button disabled={loading || !valid} className="if-button-primary min-h-11 w-full rounded-xl font-bold disabled:opacity-50">{loading ? 'Salvando...' : 'Redefinir senha'}</button></form>}<button onClick={onBack} className="action-text text-xs inline-flex items-center gap-1.5"><ArrowLeft className="h-3.5 w-3.5" />Voltar para o login</button></div></div>;
};
